Repository SidOfc/carbon.nvim, pull requests merged in 2022-11, with the labels that each got.

#97 try pinning stylua version for gh actions
  .github/workflows/ci.yml
Labels: bug

#95 Fix make some color groups more protable
  lua/carbon/settings.lua
Labels: improvement

#98 Update documentation for changed setting defaults (#95)
  doc/carbon.txt
Labels: documentation

#100 feature/close dir from cursor position
  README.md
  doc/assets/carbon-close-parent-action.gif
  doc/carbon.txt
  lua/carbon.lua
  lua/carbon/settings.lua
  test/specs/carbon_spec.lua
Labels: feature

#99 Fix better defaults
  README.md
  doc/carbon.txt
  lua/carbon/settings.lua
  test/specs/buffer_spec.lua
  test/specs/settings_spec.lua
Labels: improvement

#103 patch/buffer/symlink status
  lua/carbon.lua
  lua/carbon/buffer.lua
  lua/carbon/entry.lua
Labels: bug

#104 Bump version to 0.16.1
  doc/carbon.txt
Labels: release
