Repository SidOfc/carbon.nvim, pull requests merged in 2023-01, with the labels that each got.

#114 Add special vim.g.carbon_lazy_init setting to handle differences in plugin manager load orders (#113)
  doc/carbon.txt
  lua/carbon.lua
  plugin/carbon.vim
Labels: bug

#116 feature/explore right
  README.md
  doc/carbon.txt
  lua/carbon.lua
  lua/carbon/buffer.lua
  lua/carbon/settings.lua
  test/specs/carbon_spec.lua
Labels: feature

#118 patch/tree indent
  dev/init.lua
  lua/carbon/buffer.lua
  lua/carbon/settings.lua
Labels: bug

#119 chore: add lazy.nvim plugin manager to readme table
  README.md
Labels: documentation

#120 patch/file icon docs
  README.md
  doc/carbon.txt
Labels: documentation
